### ISSUE TITLE
Client Adapter - viewer mode

### ISSUE THREAD

**Issue by levozavr** [robot-lab/rcs-remote-control-center#33]
Реализовать возможность подключения в режиме зрителя для множества клиентов и только для одного в режиме управления.

(!)Обговорить протокол общения с unity

**upd:**
в данной задаче надо реализовать следующий функционал для client_adaptera:

- [x]  параллельное подключение как минимум двух клиентов
- [x] корректная обработка команд из стандартного протокола для каждого из них

**Comment by Vasar007** [comment]
@levozavr, такой кейс: подключилось N клиентов, один из них решил отключиться и перед отключением кинул команду `send_exit`. Что в таком случае делать ClientAdapter?

**Comment by levozavr** [comment]
@Vasar007 по идее он должен проигнорировать ее

**Comment by Vasar007** [comment]
@levozavr, что там по самой процедуре "прослушивания"?
Обработку нескольких клиентов сделал.
