### ISSUE TITLE
planner - discuss commands

### ISSUE THREAD

**Issue by levozavr** [robot-lab/rcs-remote-control-center#39]
Здесь надо определиться с набором команд для планера:

**"m X Y Z W P R c"** #31 

**"m $cube1$ + X Y Z W P R ! c"** #38 

**"m $cube1$ c"** #32 

Ваши предложения?

**Comment by Vasar007** [comment]
Больше и не надо!)

**Comment by danila19991** [comment]
Сейчас CU принимает команду по передвижению для телеги в формате `m wasX wasY ? ? ? ? gotoX gotoY ? ...` где `wasX` и `wasY` - предыдущие координаты телеги, `gotoX` и `gotoY` - координаты телеги для перехода, `?` - одно число с плавающей точкой, `? ...` неопределенное количество(>=0) чисел с плавающей точкой разделенных пробелом

**Comment by Vasar007** [comment]
Если эту команду можно засунуть в сценарий задачи, то мы вам просто это перешлём, т.к. мы не проверяем содержимое сценария.

**Comment by levozavr** [comment]
@Vasar007 так не получится, поскольку откуда мы знаем в сценарии текущее местоположение тележки?

**Comment by Vasar007** [comment]
Я просто сказал, что мы сможем переслать то, что пришлёт Юнити. А вопрос о положении телеги мы уже поднимали, правда, я не помню, чем тот спор закончился. Обратитесь к Владу и Тимуру, они об этом спорили на прошлой встрече в субботу.

**Comment by levozavr** [comment]
@danila19991 @Vasar007  как вы отнесетесь команде `m $telege$ gotoX gotoY ? ...`
Где `$telega$` - параметр?

**Comment by Vasar007** [comment]
Что такое `? ...`?

**Comment by levozavr** [comment]
@Vasar007 

> `?` - одно число с плавающей точкой, `? ...` неопределенное количество(>=0) чисел с плавающей точкой разделенных пробелом

**Comment by danila19991** [comment]
@levozavr как вы `$telege$` обновлять будете?

> @danila19991 @Vasar007 как вы отнесетесь команде `m $telege$ gotoX gotoY ? ...`
> Где `$telega$` - параметр?

**Comment by levozavr** [comment]
@danila19991 от самой телеги или фанука?

**Comment by Vasar007** [comment]
@danila19991 
>  А вопрос о положении телеги мы уже поднимали, правда, я не помню, чем тот спор закончился. Обратитесь к Владу и Тимуру, они об этом спорили на прошлой встрече в субботу.

**Comment by Vasar007** [comment]
> @Vasar007
> 
> > `?` - одно число с плавающей точкой, `? ...` неопределенное количество(>=0) чисел с плавающей точкой разделенных пробелом

Тогда это будет работать и сейчас.

**Comment by levozavr** [comment]
@ptrdiff или @OlegMoiseev 
как можно узнать текущее положение телеги от самой телеги?

**Comment by danila19991** [comment]
@ptrdiff что скажете об этом?

> Я просто сказал, что мы сможем переслать то, что пришлёт Юнити. А вопрос о положении телеги мы уже поднимали, правда, я не помню, чем тот спор закончился. Обратитесь к Владу и Тимуру, они об этом спорили на прошлой встрече в субботу.

**Comment by levozavr** [comment]
@danila19991 мы сами кстати можем обновлять `$telega$` когда посылаем его на телегу (ведь телега должна прийти в ту точку с некоторой погрешностью....)

**Comment by ptrdiff** [comment]
Влад предлагал положение телеги определять навесив на неё метку и чтобы фанук в начале осмотр произвел нашел телегу и с СТЗ положил ее координаты. 
Однако если смотреть на схемы от спииран, вообще должна быть "парковка телеги".))

**Comment by Vasar007** [comment]
Ок, тогда к чему мы в итоге пришли?

**Comment by ptrdiff** [comment]
Смогут ли ребята с телегой обеспечить одно место с которого телега будет стартовать. Как домашняя позиция у фанука.

**Comment by Vasar007** [comment]
Это вопрос или утверждение?)

**Comment by Vasar007** [comment]
Обсуждения закончены.
