### ISSUE TITLE
Planner - check command ending

### ISSUE THREAD

**Issue by levozavr** [robot-lab/rcs-remote-control-center#43]
Надо сделать то, что бы планер проверял завершилась команда или нет, 
то есть по истечению времени заложенного в команду он обращался к 3d scene и узнавал у неё информацию по положению робота, если его положение отличалось от заданного в команде, то отправлял на сцену запись об ошибке и прекращал исполнение команд.

**Comment by Vasar007** [comment]
Done in #45
