### ISSUE TITLE
отказоустойчивость планера

### ISSUE THREAD

**Issue by levkovalenko** [robot-lab/rcs-remote-control-center#50]
В текущей версии - есть команда с параметром, мы запрашиваем параметр у 3d scene
Необходимо реализовать следующее поведение:
Если у нас нет параметра, то мы раза 3 дергаем СТЗ с периодичностью в 3 секунды, после каждого раза проверяем наличие параметра, если его нет после этих попыток, то выходим из цикла обработки команд и передаем в status ошибку.

**Comment by Vasar007** [comment]
Что значит "дёргать СТЗ"?

**Comment by Vasar007** [comment]
Решена в #51
